services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secretpass
      - DB_NAME=webbh01
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: webbh01
      MYSQL_ROOT_PASSWORD: secretpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    # nếu muốn truy cập từ host, bật mapping port; mặc định mình map 3307 -> 3306 tránh xung đột:
    ports:
      - "3307:3306"

volumes:
  db_data:
